apps/tm_account/urls.py
from django.urls import path, reverse_lazy
from .views import registration, auth_views, profile_views

app_name = 'tm_account'

urlpatterns = [
    # ex: /my-account/signup/
    path('signup/', registration.signup, name='signup'),
    
    # ex: /my-account/login/
    path('login/', auth_views.CustomLoginView.as_view(), name='login'),

    # ex: /my-account/logout/
    path('logout/', auth_views.CustomLogoutView.as_view(), name='logout'),

    # ex: /my-account/profile/
    path('profile/', profile_views.profile, name='profile'),

    # ex: /my-account/profile/edit/
    path('profile/edit/', profile_views.profile_edit, name='profile_edit'),

    # ex: /my-account/password_change/
    path('password_change/', profile_views.password_change, name='password_change'),

    # ex: /my-account/delete/
    path('delete/', profile_views.account_delete, name='account_delete'),

    # Direct Password Reset URL
    path('custom_password_reset/', auth_views.direct_password_reset, name='custom_password_reset'),
]

apps/tm_assets/urls.py
from django.urls import path

from . import views

app_name = "tm_assets"

urlpatterns = [
    path("", views.portfolio_index, name="portfolio"),
    path("allocation/", views.allocation, name="allocation"),
    path("deposits/", views.deposits_list, name="deposits_list"),
    path("stocks/", views.stocks_list, name="stocks_list"),
    path("bonds/", views.bonds_list, name="bonds_list"),
    path("deposits/create/", views.create_deposit, name="create_deposit"),
    path("deposits/<int:pk>/", views.edit_deposit, name="edit_deposit"),
    path("deposits/<int:pk>/delete/", views.delete_deposit, name="delete_deposit"),
    path("stocks/create/", views.create_stock, name="create_stock"),
    path("stocks/<int:pk>/", views.edit_stock, name="edit_stock"),
    path("stocks/<int:pk>/delete/", views.delete_stock, name="delete_stock"),
    path("bonds/create/", views.create_bond, name="create_bond"),
    path("bonds/<int:pk>/", views.edit_bond, name="edit_bond"),
    path("bonds/<int:pk>/delete/", views.delete_bond, name="delete_bond"),
    path("refresh-prices/", views.refresh_prices, name="refresh_prices"),
    path("test/", views.test_view, name="test_view"),
]

apps/tm_begin/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'tm_begin'

urlpatterns = [
    path('', views.index, name='index'),
    path("news/", views.investing_news, name="stock_news"),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
]

apps/tm_mylink/urls.py
from django.urls import path
from . import views

app_name = 'tm_mylink'

urlpatterns = [
    path('', views.inquiry_write, name='inquiry_write'),
    path('list/', views.inquiry_list, name='inquiry_list'),   
    path('detail/<int:pk>/', views.inquiry_detail, name='inquiry_detail'),
    path('edit/<int:pk>/', views.inquiry_edit, name='inquiry_edit'), 
    path('delete/<int:pk>/', views.inquiry_delete, name='inquiry_delete'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # develop 기준: allauth는 /accounts/, tm_account는 /my-account/
    path('accounts/', include('allauth.urls')),
    path('my-account/', include('apps.tm_account.urls')),
    path('', include('apps.tm_begin.urls')),
    path('inquiry/', include('apps.tm_mylink.urls')),
    # tm_assets는 별도 네임스페이스로 포함해 템플릿 역참조 안정성 확보
    path('assets/', include(('apps.tm_assets.urls', 'tm_assets'), namespace='tm_assets')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Ttiglemoa{% endblock %}</title>
    <link rel="icon" href="{% static 'images/ti_logo.png' %}" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
      crossorigin="anonymous"
    />

    <!-- Bootstrap Icons -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />

    <!-- fontawesome cdn -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
    />

    <!-- Project CSS -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/stock_news.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
    <link rel="stylesheet" href="{% static 'css/about.css' %}" />
    <link rel="stylesheet" href="{% static 'css/colors.css' %}" />

    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <!-- Navbar -->
    {% include 'common/navbar.html' %}

    <!-- Page Content -->
    <main class="container">
      {% if messages %}
      <div class="messages">
        {% for message in messages %}
        <div
          class="alert alert-{{ message.tags }} alert-dismissible fade show"
          role="alert"
        >
          {{ message }}
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="alert"
            aria-label="Close"
          ></button>
        </div>
        {% endfor %}
      </div>
      {% endif %} {% block content %} {% endblock %}
    </main>

    <!-- Footer can be added here -->
    <!-- <footer></footer> -->
    <footer>{% include 'common/footer.html' %}</footer>

    <!-- Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q"
      crossorigin="anonymous"
    ></script>

    <script src="{% static 'js/main.js' %}"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% block extra_js %}{% endblock %}
  </body>
</html>

templates/common/footer.html
{# templates/common/footer.html #}
{% load static %}

<footer class="site-footer">
  <div class="d-flex align-items-center mb-2">
    <img src="{% static 'images/financial-profit.png' %}" alt="logo" height="28" class="me-2">
    <strong class="brand">TTIGLEMOA</strong>
    <div class="theme-switch-wrapper ms-auto"> {# Added ms-auto for right alignment within flexbox #}
      <label class="theme-switch" for="theme-toggle-checkbox">
        <input type="checkbox" id="theme-toggle-checkbox" />
        <div class="slider round">
          <i class="bi bi-sun-fill sun-icon"></i>
          <i class="bi bi-moon-fill moon-icon"></i>
        </div>
      </label>
    </div>
  </div>
  <div class="container py-5">
    <div class="row g-4">
      <div class="col-12 col-lg-3">
        
        
        
        <h6 class="footer-title">팀 멤버</h6>
        <ul class="footer-links">

            <li>
                <a href="#">송원섭</a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-linkedin-in"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-instagram"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-x-twitter"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-github"></i></a>
                
            </li>


            <li>
                <a href="#">우승백</a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-linkedin-in"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-instagram"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-x-twitter"></i></i></a>
                <a href="https://github.com/Dev-Nut00" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-github"></i></a>
            </li>


            <li>
                <a href="#">임규현</a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-linkedin"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-instagram"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-x-twitter"></i></a>
                <a href="https://github.com/thlim008" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-github"></i></i></a>
            </li>

            <li>
                <a href="#">김기섭</a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-linkedin"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-instagram"></i></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-x-twitter"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-github"></i></i></a>
            </li>


            <li>
                <a href="#">이기진</a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-linkedin"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-instagram"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-square-x-twitter"></i></a>
                <a href="#" class="link-light opacity-75 hover-opacity"><i class="fa-brands fa-github"></i></a>
            </li>

        </ul>
      </div>

      <div class="col-6 col-lg-2">
        <h6 class="footer-title">인기 마켓</h6>
        <ul class="footer-links">
          <li><a href="#">미국: 나스닥</a></li>
          <li><a href="#">대한민국: 코스피</a></li>
        </ul>
      </div>

      <div class="col-6 col-lg-2">
        <h6 class="footer-title">투자 관점</h6>
        <ul class="footer-links">
          <li><a href="#">저평가주</a></li>
          <li><a href="#">배당주</a></li>
        </ul>
      </div>

      <div class="col-6 col-lg-2">
        <h6 class="footer-title">특징 & 기능</h6>
        <ul class="footer-links">
          <li><a href="#">차트분석</a></li>
          <li><a href="#">인기분석</a></li>
        </ul>
      </div>

      <div class="col-6 col-lg-3">
        <h6 class="footer-title">Team : Ttiglemoa</h6>
        <ul class="footer-links">
          <li><a href="#">구독 & 가격</a></li>
          <li><a href="{% url 'tm_begin:about' %}">팀 소개</a></li>
          <li><a href="{% url 'tm_mylink:inquiry_write' %}">문의사항</a></li>
        </ul>
      </div>
    </div>

    <hr class="footer-divider my-4">

    <div class="row gy-3 small">
      <div class="col-12 col-lg-8">
        <div class="text-secondary">
          본사이트는 학업을 위한 사이트입니다. © 2025 Ttiglemoa Pty Ltd. All rights reserved.
          <a href="https://github.com/daemonXid/ttiglemoa" class="link-underline">깃허브 소스 </a>
        </div>
      </div>
      <div class="col-12 col-lg-4 text-lg-end">
        <a href="#" class="me-3">Financial Services Guide</a>
        <a href="#" class="me-3">Terms & Conditions</a>
        <a href="#">Privacy Policy</a>
      </div>
    </div>
  </div>
</footer>

templates/common/index.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<div class="main_section flex-column mb-3">

    <div class="tv-wrap">
        {% include 'tm_begin/main_content/main_about.html' %}
    </div>
    

    {% if user.is_authenticated %}


        {% include 'tm_begin/main_content/stock_chart.html' %}

    {% else %}


        {% include 'tm_begin/main_content/stock_chart.html' %}
        {% include 'tm_begin/main_content/stock_news_main.html' %}
    
    {% endif %}

</div>
{% endblock %}

templates/common/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a href="{% url 'tm_begin:index' %}"><img class="navbar-brand navbar-logo" src="{% static 'images/main_page/ti_logo.png'%}" alt=""></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tm_begin:about' %}">소개</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tm_assets:portfolio' %}">포트폴리오</a>
        </li>

        {% endif %}


        <li class="nav-item">
          <a class="nav-link" href="{% url 'tm_begin:stock_news' %}">뉴스</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tm_mylink:inquiry_list' %}">문의하기</a>
        </li>
      </ul>

      <form class="d-flex" action="{% url 'tm_begin:search' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="검색" aria-label="Search"/>
        <button class="btn btn-outline-primary btn-sm btn-search me-2" type="submit">검색</button>
      </form>

        <ul class="navbar-nav mb-2 mb-lg-0 align-items-center">
        {% if user.is_authenticated %}
          <li class="nav-item">
              <a class="nav-link d-flex align-items-center" href="{% url 'tm_account:profile' %}">
                  {% if user.profile_image %}
                                            <img src="{{ user.profile_image.url }}" onerror="this.onerror=null;this.src='{% static 'images/avatars/avatar1.svg' %}'" alt="Profile Image" class="rounded-circle me-2" width="30" height="30" style="object-fit: cover;">

                  {% else %}
                      <img src="{% static 'images/avatars/avatar2.svg' %}" alt="Default Avatar" class="rounded-circle me-2" width="30" height="30">
                  {% endif %}
                  프로필({{ user.nickname }})
              </a>
          </li>
          <li class="nav-item me-2">
            <form action="{% url 'tm_account:logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-outline-secondary btn-sm nav_btn_signup">로그아웃</button>
            </form>
          </li>
        {% else %}
          <li class="nav-item me-2 nav-login">
            <a href="{% url 'tm_account:login' %}">
              <button class="btn btn-outline-primary nav_btn_signup ">로그인</button>
            </a>
          </li>
          <li class="nav-item me-2 nav-signup">
            <a href="{% url 'tm_account:signup' %}">
              <button class="btn btn-primary nav_btn_signup ">회원가입</button>
            </a>
          </li>
        {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>